home:
  path: /
  parameters: {}
  controller: Application\Controller\DefaultController
  action: home
bookList:
  path: /book
  parameters: {}
  controller: Application\Controller\BookController
  action: list
book:
  path: /book/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\BookController
  action: book
chapter:
  path: /chapter/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\ChapterController
  action: chapter
login:
  path: /login
  parameters: {}
  controller: Application\Controller\UserController
  action: login
logout:
  path: /logout
  parameters: {}
  controller: Application\Controller\UserController
  action: logout
admin:
  path: /admin
  parameters: {}
  controller: Application\Controller\AdminController
  action: panel
adminBook:
  path: /admin/book
  parameters: {}
  controller: Application\Controller\Manage\BookController
  action: book
adminChapter:
  path: /admin/chapter
  parameters: {}
  controller: Application\Controller\Manage\ChapterController
  action: chapter
adminComment:
  path: /admin/comment
  parameters: {}
  controller: Application\Controller\Manage\CommentController
  action: comment
adminUser:
  path: /admin/user
  parameters: {}
  controller: Application\Controller\Manage\UserController
  action: user
adminContent:
  path: /admin/content/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\ChapterController
  action: content
password:
  path: /password/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\UserController
  action: pass
passwordChange:
  path: /password/change/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\UserController
  action: passChange
persistBook:
  path: /admin/book/persist
  parameters: {}
  controller: Application\Controller\Manage\BookController
  action: persist
removeBook:
  path: /admin/book/remove
  parameters: {}
  controller: Application\Controller\Manage\BookController
  action: delete
addChapter:
  path: /admin/chapter/create
  parameters: {}
  controller: Application\Controller\Manage\ChapterController
  action: create
editChapter:
  path: /admin/chapter/edit
  parameters: {}
  controller: Application\Controller\Manage\ChapterController
  action: edit
removeChapter:
  path: /admin/chapter/remove
  parameters: {}
  controller: Application\Controller\Manage\ChapterController
  action: delete
updateContent:
  path: /admin/content/update/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\ChapterController
  action: contentUpdate
createComment:
  path: /comment/create/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\CommentController
  action: commentCreate
removeComment:
  path: /admin/comment/remove/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\CommentController
  action: commentRemove
likeComment:
  path: /comment/like/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\CommentController
  action: commentLikeReport
reportComment:
  path: /comment/report/:id
  parameters: {id: '[\d]+'}
  controller: Application\Controller\Manage\CommentController
  action: commentLikeReport
loginSend:
  path: /login/send
  parameters: {}
  controller: Application\Controller\UserController
  action: loginSend
userAdd:
  path: /admin/user/create
  parameters: {}
  controller: Application\Controller\Manage\UserController
  action: add
userEdit:
  path: /admin/user/edit
  parameters: {}
  controller: Application\Controller\Manage\UserController
  action: edit
userRemove:
  path: /admin/user/remove
  parameters: {}
  controller: Application\Controller\Manage\UserController
  action: remove
userReset:
  path: /admin/user/reset
  parameters: {}
  controller: Application\Controller\Manage\UserController
  action: reset